chili-publish/studio-ui

package.json, yarn.lock
This PR bumps shared components version
=> [Fix] bump shared components version

src/components/itemBrowser/ItemBrowser.tsx
This PR handles the nextpage token when it is not a URL
-   [WRS-1464](https://chilipublishintranet.atlassian.net/browse/WRS-1464)
[WRS-1464]: https://chilipublishintranet.atlassian.net/browse/WRS-1464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix] [WRS-1464] Fix next page token

package.json, yarn.lock
This PR bumps the SDK version for release
=> [Fix] Bump SDK version

src/components/navbar/downloadPanel/DownloadPanel.styles.tsx, src/components/navbar/downloadPanel/DropdownOption.tsx, src/components/navbar/downloadPanel/useDownload.tsx, src/components/shared/StudioDropdown.styles.tsx
This PR Truncates output settings option name and description, in the output settings dropdown menu
-   [WRS-1471](https://chilipublishintranet.atlassian.net/browse/WRS-1471)
[WRS-1471]: https://chilipublishintranet.atlassian.net/browse/WRS-1471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Feature] [WRS-1471] Truncate output settings option name and description

src/components/navbar/downloadPanel/useDownload.tsx
=> [Fix] remove placeholder description

package.json, yarn.lock
This PR bumps the sdk to version 1.4.4
=> [Fix] Bump SDK to 1.4.4

src/components/imagePanel/ImagePanel.tsx, src/components/variablesComponents/imageVariable/ImageVariable.tsx
This PR Uses correct media download type `MediaDownloadType.mediumres`
-   [WRS-1540](https://chilipublishintranet.atlassian.net/browse/WRS-1540)
[WRS-1540]: https://chilipublishintranet.atlassian.net/browse/WRS-1540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix] [WRS-1540] Use correct media download type

.github/workflows/dev-stg-build.yml, package.json, yarn.lock
This PR bumps the SDK for release
=> [Release] Bump SDK for release

package.json, yarn.lock
This PR fixes zoominfo extension on CGX
-   [GRAFX-2765](https://chilipublishintranet.atlassian.net/browse/GRAFX-2765)
[GRAFX-2765]: https://chilipublishintranet.atlassian.net/browse/GRAFX-2765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix] Fix zoominfo extension on CGX

.github/workflows/automated-tests.yml
This PR
-   [GRAFX-2715](https://chilipublishintranet.atlassian.net/browse/GRAFX-2715)
[GRAFX-2715]: https://chilipublishintranet.atlassian.net/browse/GRAFX-2715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add new workflow for the automated tests

src/StudioProjectLoader.tsx, src/tests/StudioProjectLoader.test.tsx
This PR Enables autosaving in dev
-   [WRS-1565](https://chilipublishintranet.atlassian.net/browse/WRS-1565)
[WRS-1565]: https://chilipublishintranet.atlassian.net/browse/WRS-1565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FIX] [WRS-1565] Enable autosaving in dev

index.html, src/components/itemBrowser/ItemBrowser.tsx
This PR formats the relative path if the the name of the folder is not included in the `relativePath`
-   [WRS-1557](https://chilipublishintranet.atlassian.net/browse/WRS-1557)
[WRS-1557]: https://chilipublishintranet.atlassian.net/browse/WRS-1557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix] [WRS-1557] Handle scenario when name is not available in relative path

index.html, src/components/itemBrowser/ItemBrowser.styles.tsx, src/components/itemBrowser/ItemBrowser.tsx, src/contexts/VariablePanelContext.tsx, src/contexts/VariablePanelContext.types.tsx
This PR  Media search improvements in Studio UI, the improvements are as follows:
- Prevent duplicated calls when opening image picker.
- Fix spacing between breadcrumb and input.
- reset search when going out of browsing elements.
-   [WRS-1602](https://chilipublishintranet.atlassian.net/browse/WRS-1602)
[WRS-1602]: https://chilipublishintranet.atlassian.net/browse/WRS-1602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix] [WRS-1602] Media search improvements in Studio UI

package.json, yarn.lock
This PR bumps engine and sdk for a hotfix
=> [Fix] Bump SDK for hotfix 1.6.2

package.json, yarn.lock
I have created this pull request on a best-effort basis to help unblock Studio UI.
This PR integrates https://github.com/chili-publish/studio-sdk/pull/426
-   [WRS-1639](https://chilipublishintranet.atlassian.net/browse/WRS-1639)
[WRS-1639]: https://chilipublishintranet.atlassian.net/browse/WRS-1639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix] [WRS-1639] List variable display value (backwards compatibility)

package.json, src/components/navbar/downloadPanel/useDownload.tsx, src/tests/navbar/useDownload.test.tsx, src/utils/documentExportHelper.ts, yarn.lock
This PR adds PDF as the export setting
=> [Fix][WRS-1658] Add PDF export (out of experimental)

package.json, yarn.lock
=> [Fix] Bump up SDK version

package.json, yarn.lock
This PR bumps the sdk to 1.8.1
=> [Fix] Bump SDK to 1.8.1

README.md, index.html, package.json, src/_dev-execution/bootstrap.ts, src/_dev-execution/token-manager.ts, src/components/variablesComponents/imageVariable/ImageVariable.tsx, src/main.tsx, vite.config.ts, yarn.lock
This PR
-   [GRAFX-3215](https://chilipublishintranet.atlassian.net/browse/GRAFX-3215)
[GRAFX-3215]: https://chilipublishintranet.atlassian.net/browse/GRAFX-3215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix][GRAFX-3215] Token refresh for dev mode

package.json, yarn.lock
This PR bumps the SDK version to 1.9.1
=> [Feature] Bump SDK version to 1.9.1

package.json, src/components/variablesComponents/imageVariable/ImageVariable.tsx, src/components/variablesComponents/useVariablesComponents.ts, src/tests/LeftPanel.test.tsx, src/tests/VariablesComponents.test.tsx, src/tests/VariablesList.test.tsx, yarn.lock
This PR
-   [WRS-1228](https://chilipublishintranet.atlassian.net/browse/WRS-1228)
[WRS-1228]: https://chilipublishintranet.atlassian.net/browse/WRS-1228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix][WRS-1228] Make image picker more stable

src/DemoDocumentLoader.tsx, src/StudioProjectLoader.tsx, src/components/navbar/downloadPanel/DownloadPanel.tsx, src/components/navbar/downloadPanel/useDownload.tsx, src/components/navbar/useNavbar.tsx, src/main.tsx, src/tests/StudioProjectLoader.test.tsx, src/types/types.ts, src/utils/documentExportHelper.ts
This PR
-   [WRS-1764](https://chilipublishintranet.atlassian.net/browse/WRS-1764)
[WRS-1764]: https://chilipublishintranet.atlassian.net/browse/WRS-1764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix] [WRS-1764] Use userInterfaceId and outputSettings id in document download

package.json, yarn.lock
=> [Fix] Bump SDK version to 1.10.1

src/StudioProjectLoader.tsx, src/types/types.ts
This PR Selects the default user interface if the original one linked to the project is deleted
-   [WRS-1851](https://chilipublishintranet.atlassian.net/browse/WRS-1851)
[WRS-1851]: https://chilipublishintranet.atlassian.net/browse/WRS-1851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix] [WRS-1851] Revert to default user interface 

src/StudioProjectLoader.tsx
This PR will show the output settings of `default user interface` when `userInterfaceId` is null
-   [WRS-1854](https://chilipublishintranet.atlassian.net/browse/WRS-1854)
[WRS-1854]: https://chilipublishintranet.atlassian.net/browse/WRS-1854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix] [WRS-1854] Default to default user interface when id not provided

README.md, documentation/advanced-integration.md, src/App.tsx, src/StudioProjectLoader.tsx, src/main.tsx, src/tests/StudioProjectLoader.test.tsx, src/types/types.ts, src/utils/documentExportHelper.ts
This PR
-   [WRS-1861](https://chilipublishintranet.atlassian.net/browse/WRS-1861)
[WRS-1861]: https://chilipublishintranet.atlassian.net/browse/WRS-1861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix][WRS-1861] Make refresh token action optional

src/App.tsx, src/components/variablesComponents/imageVariable/ImageVariable.tsx, src/components/variablesComponents/imageVariable/useMediaDetails.ts, src/components/variablesComponents/imageVariable/usePreviewImageUrl.ts, src/components/variablesComponents/useVariablesComponents.ts, src/contexts/Subscriber.tsx, src/contexts/VariablePanelContext.types.tsx, src/core/hooks/useVariablesChange.ts, src/tests/LeftPanel.test.tsx, src/tests/VariablesComponents.test.tsx, src/tests/VariablesList.test.tsx, src/tests/components/variablesComponents/imageVariable/ImageVariable.test.tsx, src/tests/components/variablesComponents/imageVariable/useMediaDetails.test.ts, src/tests/components/variablesComponents/imageVariable/usePreviewImageUrl.test.ts, src/tests/core/hooks/useVariablesChange.test.ts, src/utils/subscriber.ts
This PR
-   [WRS-1766](https://chilipublishintranet.atlassian.net/browse/WRS-1766)
[WRS-1766]: https://chilipublishintranet.atlassian.net/browse/WRS-1766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix][WRS-1766] Reflect image frame value on variables updates

src/components/variablesComponents/NumberVariable.tsx, src/components/variablesComponents/VariablesComponents.types.ts, src/components/variablesComponents/useVariablesComponents.ts
This PR Fixes the issue with number variable change which adds 3 actions are added to undo stack, it also remove casting and use the correct typing for number variables
-   [WRS-1878](https://chilipublishintranet.atlassian.net/browse/WRS-1878)
[WRS-1878]: https://chilipublishintranet.atlassian.net/browse/WRS-1878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix] [WRS-1878] Fix number variable change adds 3 actions are added to undo stack

package.json, src/components/variablesComponents/imageVariable/useMediaDetails.ts, yarn.lock
=> [Fix] Bump SDK version to 1.11.0

src/components/variablesComponents/imageVariable/useMediaDetails.ts
This PR
-   [WRS-1821](https://chilipublishintranet.atlassian.net/browse/WRS-1821)
[WRS-1821]: https://chilipublishintranet.atlassian.net/browse/WRS-1821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix][WRS-1821] Strict typings for connector's mappings

package.json, src/App.tsx, src/components/variables/VariablesList.tsx, src/components/variablesComponents/imageVariable/useMediaDetails.ts, src/tests/VariablesList.test.tsx, src/tests/mocks/mockVariables.ts, yarn.lock
This PR
-   [WRS-1761](https://chilipublishintranet.atlassian.net/browse/WRS-1761)
[WRS-1761]: https://chilipublishintranet.atlassian.net/browse/WRS-1761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Feat][WRS-1761] Support "displayValues" for list variable items

package.json, yarn.lock
This PR fixes https://chilipublishintranet.atlassian.net/browse/MAIN-673
=> [Fix] Fix loading template in Chrome (#169)

src/components/variablesComponents/DateVariable.tsx, src/tests/VariablesComponents.test.tsx
=> [Fix] add locale to datepicker

package.json, yarn.lock
This PR set SDK to new minor version 1.12.x
=> [Fix] Bump SDK version to 1.12.x

package.json, src/tests/VariablesComponents.test.tsx, yarn.lock
=> [Fix] Switch connectors to v1

.github/workflows/dev-stg-build.yml, .github/workflows/pr-build.yml, .github/workflows/production-build.yml, README.md, package.json, yarn.lock
This PR updates node version
-   [GRAFX-3403](https://chilipublishintranet.atlassian.net/browse/GRAFX-3403)
[GRAFX-3403]: https://chilipublishintranet.atlassian.net/browse/GRAFX-3403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Feature] [GRAFX-3403] Update node version

src/components/variablesComponents/NumberVariable.tsx
This PR  Ignore decimal separator on inputs
-   [WRS-1943](https://chilipublishintranet.atlassian.net/browse/WRS-1943)
[WRS-1943]: https://chilipublishintranet.atlassian.net/browse/WRS-1943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix] [WRS-1943] Ignore decimal separator on inputs

README.md, package.json, src/components/itemBrowser/ItemBrowser.tsx, vite.config.ts, yarn.lock
This PR
-   [WRS-1808](https://chilipublishintranet.atlassian.net/browse/WRS-1808)
[WRS-1808]: https://chilipublishintranet.atlassian.net/browse/WRS-1808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix] switch to new shared components lib

.github/workflows/dev-stg-build.yml, .github/workflows/production-build.yml, validate_versions.cjs
This PR cleans up some stuff after the release of 1.13.0
=> [Fix] Post release cleanup for actions

src/App.tsx, src/MainContent.styles.tsx, src/MainContent.tsx, src/components/connector-authentication/index.ts, src/components/connector-authentication/useConnectorAuthentication.ts, src/components/connector-authentication/useConnectorAuthenticationResult.ts, src/tests/components/connector-authentication/useConnectorAuthentication.test.ts, src/tests/integration/StudioLoaderExpiredToken.test.tsx
This PR
-   [WRS-1897](https://chilipublishintranet.atlassian.net/browse/WRS-1897)
[WRS-1897]: https://chilipublishintranet.atlassian.net/browse/WRS-1897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Feat][WRS-1897] Show error toast for failed connector's authorization

src/components/itemBrowser/ItemBrowser.tsx, src/components/variablesComponents/imageVariable/useMediaDetails.ts, src/tests/LeftPanel.test.tsx, src/tests/components/variablesComponents/imageVariable/useMediaDetails.test.ts, src/tests/integration/StudioLoaderValidToken.test.tsx
This PR fixes media connector without filtering capability
-   [WRS-1899](https://chilipublishintranet.atlassian.net/browse/WRS-1899)
[WRS-1899]: https://chilipublishintranet.atlassian.net/browse/WRS-1899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix] [WRS-1899] Media connector without filtering capability

package.json, src/tests/LeftPanel.test.tsx, yarn.lock
=> [Feature] Bump SDK version to 1.15.x

.github/CODEOWNERS, src/tests/LeftPanel.test.tsx, src/utils/documentExportHelper.ts
This PR
-   [WRS-2008](https://chilipublishintranet.atlassian.net/browse/WRS-2008)
[WRS-2008]: https://chilipublishintranet.atlassian.net/browse/WRS-2008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix] Add project id to output call

package.json
=> [Fix] Change version to 1.15.1-rc.0 for hotfix release

src/components/navbar/downloadPanel/DownloadPanel.styles.tsx
This PR
-   [WRS-1961](https://chilipublishintranet.atlassian.net/browse/WRS-1961)
[WRS-1961]: https://chilipublishintranet.atlassian.net/browse/WRS-1961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FIX] [WRS-1961] Download modal background color changed to #FFFFFF

package.json, src/components/shared/StudioMobileDropdown/StudioMobileDropdown.styles.ts
This PR
-   [WRS-1941](https://chilipublishintranet.atlassian.net/browse/WRS-1941)
[WRS-1941]: https://chilipublishintranet.atlassian.net/browse/WRS-1941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Bugfix] [WRS-1941] updated shared components

src/tests/LeftPanel.test.tsx
This PR  Fix leftPanel flaky test
=> [Fix] [NO-TICKET] Fix leftPanel flaky test

package.json, yarn.lock
This PR
-   [WRS-2065](https://chilipublishintranet.atlassian.net/browse/WRS-2065)
[WRS-2065]: https://chilipublishintranet.atlassian.net/browse/WRS-2065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix] [WRS-2065] Updates to shared components with new modal layout

vite.config.ts
=> [Fix] Fix dev mode

src/contexts/ShortcutManager/ShortcutProvider.tsx
This PR Prevents handling shortcuts when typing inside inputs
-   [WRS-2127](https://chilipublishintranet.atlassian.net/browse/WRS-2127)
[WRS-2127]: https://chilipublishintranet.atlassian.net/browse/WRS-2127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix] [WRS-2127] Prevent shortcuts on inputs

package.json, src/contexts/ShortcutManager/ShortcutProvider.tsx, yarn.lock
This PR Selects correct iframe when in design mode
-   [WRS-2127](https://chilipublishintranet.atlassian.net/browse/WRS-2127)
[WRS-2127]: https://chilipublishintranet.atlassian.net/browse/WRS-2127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix] [WRS-2127] Select correct iframe in design mode

package.json, yarn.lock
This PR Fix timeline position
-   [WRS-2139](https://chilipublishintranet.atlassian.net/browse/WRS-2139)
[WRS-2139]: https://chilipublishintranet.atlassian.net/browse/WRS-2139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix] [WRS-2139] Fix timeline position

package.json, yarn.lock
This PR preps for the 1.17 release
=> [Release] Prep for 1.17

src/_dev-execution/bootstrap.ts, src/components/variablesComponents/BooleanVariable.tsx, src/components/variablesComponents/NumberVariable.tsx, src/components/variablesComponents/TextVariable.tsx, src/components/variablesComponents/dateVariable/DateVariable.tsx, src/components/variablesComponents/imageVariable/ImageVariable.tsx, src/components/variablesComponents/listVariable/ListVariable.tsx, src/components/variablesComponents/listVariable/MobileListVariable.tsx, src/tests/VariablesComponents.test.tsx, src/tests/VariablesList.test.tsx, src/tests/components/variablesComponents/booleanVariable/BooleanVariable.test.tsx, src/tests/components/variablesComponents/dateVariable/DateVariable.test.tsx, src/tests/components/variablesComponents/imageVariable/ImageVariable.test.tsx, src/tests/components/variablesComponents/listVariable/ListVariable.test.tsx, src/tests/components/variablesComponents/numberVariable/NumberVariable.test.tsx, src/tests/components/variablesComponents/textVariable/TextVariable.test.tsx, src/tests/mocks/mockVariables.ts
This PR
-   [WRS-2154](https://chilipublishintranet.atlassian.net/browse/WRS-2154)
[WRS-2154]: https://chilipublishintranet.atlassian.net/browse/WRS-2154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix][WRS-2154] Use variable name as label as a fallback

src/StudioProjectLoader.tsx, src/components/navbar/navbarItems/useUserInterfaceSelector.tsx, src/components/navbar/studioNavbar/useStudioNavbar.tsx, src/utils/constants.ts
This PR
-   [WRS-2133](https://chilipublishintranet.atlassian.net/browse/WRS-2133)
[WRS-2133]: https://chilipublishintranet.atlassian.net/browse/WRS-2133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WRS-2133 - session store selected user interface

package.json, src/tests/components/dataSource/DataSourceModal.test.tsx, yarn.lock
This PR  Updates GSC version to fix DatePicker style
-   [WRS-2222](https://chilipublishintranet.atlassian.net/browse/WRS-2222)
[WRS-2222]: https://chilipublishintranet.atlassian.net/browse/WRS-2222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix] [WRS-2222] Update GSC version to fix DatePicker style

src/MainContent.tsx, src/components/navbar/Navbar.tsx, src/components/navbar/Navbar.types.ts, src/components/navbar/studioNavbar/StudioNavbar.tsx, src/components/navbar/studioNavbar/useStudioNavbar.tsx, src/components/navbar/useDownloadPanel.ts, src/tests/navbar/Navbar.test.tsx
This PR
-   [WRS-2174](https://chilipublishintranet.atlassian.net/browse/WRS-2174)
[WRS-2174]: https://chilipublishintranet.atlassian.net/browse/WRS-2174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix][WRS-2174] Use project name as file name for outputs

src/components/dataSource/useDataSource.ts, src/tests/components/dataSource/DataSource.test.tsx, src/tests/components/dataSource/DataSourceModal.test.tsx, src/tests/components/dataSource/MobileDataSourceTray.test.tsx
This PR
-   [WRS-2123](https://chilipublishintranet.atlassian.net/browse/WRS-2123)
[WRS-2123]: https://chilipublishintranet.atlassian.net/browse/WRS-2123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix][WRS-2123] Use DataSource API to operate with configured data source for project

package.json, src/MainContent.tsx, src/components/dataSource/useDataSource.ts, src/tests/components/dataSource/DataSource.test.tsx, src/tests/components/dataSource/DataSourceModal.test.tsx, src/tests/components/dataSource/MobileDataSourceTray.test.tsx, src/tests/components/dataSource/useDataSource.test.ts, src/types/SDKError.ts, src/utils/subscriber.ts, yarn.lock
This PR
-   [WRS-2176](https://chilipublishintranet.atlassian.net/browse/WRS-2176)
[WRS-2176]: https://chilipublishintranet.atlassian.net/browse/WRS-2176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix][WRS-2176] Show correct selection for data source when doing undo/redo

package.json, src/components/dataSource/DataSourceTable.tsx, yarn.lock
This PR
-   [WRS-2253](https://chilipublishintranet.atlassian.net/browse/WRS-2253)
[WRS-2253]: https://chilipublishintranet.atlassian.net/browse/WRS-2253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix][WRS-2253] Update visualization for data source cells

src/_dev-execution/bootstrap.ts, src/components/variablesComponents/BooleanVariable.tsx, src/components/variablesComponents/NumberVariable.tsx, src/components/variablesComponents/TextVariable.tsx, src/components/variablesComponents/dateVariable/DateVariable.tsx, src/components/variablesComponents/imageVariable/ImageVariable.tsx, src/components/variablesComponents/listVariable/ListVariable.tsx, src/components/variablesComponents/listVariable/MobileListVariable.tsx, src/tests/VariablesComponents.test.tsx, src/tests/VariablesList.test.tsx, src/tests/components/variablesComponents/booleanVariable/BooleanVariable.test.tsx, src/tests/components/variablesComponents/dateVariable/DateVariable.test.tsx, src/tests/components/variablesComponents/imageVariable/ImageVariable.test.tsx, src/tests/components/variablesComponents/listVariable/ListVariable.test.tsx, src/tests/components/variablesComponents/numberVariable/NumberVariable.test.tsx, src/tests/components/variablesComponents/textVariable/TextVariable.test.tsx
This PR
-   [WRS-2228](https://chilipublishintranet.atlassian.net/browse/WRS-2228)
[WRS-2228]: https://chilipublishintranet.atlassian.net/browse/WRS-2228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Task][WRS-2228] old studio ff cleanup

package.json, yarn.lock
This PR Integrates SDK with multiple event subscriptions support
-   [WRS-2212](https://chilipublishintranet.atlassian.net/browse/WRS-2212)
[WRS-2212]: https://chilipublishintranet.atlassian.net/browse/WRS-2212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Feature] [WRS-2212] Integrate SDK with multiple event subscriptions support

documentation/advanced-integration.md
This PR
-   [GRAFX-4173](https://chilipublishintranet.atlassian.net/browse/GRAFX-4173)
[GRAFX-4173]: https://chilipublishintranet.atlassian.net/browse/GRAFX-4173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Feature] [GRAFX-4173] Document theming

src/App.tsx, src/styles/GlobalStyle.ts
This PR will fix all external styling
=> [Fix] Remove external styling

src/_dev-execution/bootstrap.ts, src/components/layout-panels/leftPanel/LeftPanel.tsx, src/components/variables/MobileVariablesTray.tsx, src/tests/components/dataSource/MobileDataSourceTray.test.tsx
This PR
-   [GRAFX-4110](https://chilipublishintranet.atlassian.net/browse/GRAFX-4110)
[GRAFX-4110]: https://chilipublishintranet.atlassian.net/browse/GRAFX-4110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [GRAFX-4110] change FF casing

package.json, yarn.lock
=> [Bump] New sdk

package.json, yarn.lock
This PR makes preparations for release
=> [Release] Prep for 1.20

documentation/advanced-integration.md
=> [Fix] Theming documentation

package.json
=> [Fix] Revert version of the package

src/MainContent.tsx, src/_dev-execution/bootstrap.ts
=> [Fix] Use default options for LayoutSection

package.json, yarn.lock
This PR Upgrade ts version
-   [GRAFX-3252](https://chilipublishintranet.atlassian.net/browse/GRAFX-3252)
[GRAFX-3252]: https://chilipublishintranet.atlassian.net/browse/GRAFX-3252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix] [GRAFX-3252] Upgrade ts

src/components/dataSource/useDataSource.ts, src/components/variables/MobileVariablesList.tsx, src/components/variables/VariablesList.tsx
This PR
-   [WRS-2306](https://chilipublishintranet.atlassian.net/browse/WRS-2306)
[WRS-2306]: https://chilipublishintranet.atlassian.net/browse/WRS-2306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix][WRS-2306] Run validation of the variables after data row change

package.json, yarn.lock
This PR Integrates select blur fix
-   [WRS-2278](https://chilipublishintranet.atlassian.net/browse/WRS-2278)
[WRS-2278]: https://chilipublishintranet.atlassian.net/browse/WRS-2278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix] [WRS-2278] Integrate select blur fix

package.json, yarn.lock
This PR
-   [WRS-2378](https://chilipublishintranet.atlassian.net/browse/WRS-2378)
[WRS-2378]: https://chilipublishintranet.atlassian.net/browse/WRS-2378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix][WRS-2378] Fix context menu outline

src/_dev-execution/bootstrap.ts, src/components/layout-panels/leftPanel/LeftPanel.tsx, src/components/variables/MobileVariablesTray.tsx, src/contexts/AppProvider.tsx, src/tests/MobileVariableTrayLayout.test.tsx, src/tests/components/dataSource/MobileDataSourceTray.test.tsx
This PR removes studioDataSource feature flag
-   [GRAFX-4334](https://chilipublishintranet.atlassian.net/browse/GRAFX-4334)
[GRAFX-4334]: https://chilipublishintranet.atlassian.net/browse/GRAFX-4334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix][GRAFX-4334] Remove studioDataSource feature flag

package.json, yarn.lock
=> [Release] Prep for 1.22

package.json, src/components/variablesComponents/MultiLineTextVariable.tsx, yarn.lock
This PR  Add error message to required MultiLine text variables
-   [WRS-2382](https://chilipublishintranet.atlassian.net/browse/WRS-2382)
[WRS-2382]: https://chilipublishintranet.atlassian.net/browse/WRS-2382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix] [WRS-2382] Add error message to required MultiLine text variables

package.json, yarn.lock
=> [Release] 1.23

src/core/hooks/useLayoutSection.ts, src/tests/LayoutSectionUIOptions.test.tsx, src/tests/core/hooks/useLayoutSection.test.ts
This PR
-   [WRS-2429](https://chilipublishintranet.atlassian.net/browse/WRS-2429)
[WRS-2429]: https://chilipublishintranet.atlassian.net/browse/WRS-2429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix][WRS-2429] Hide layouts section for All layouts mode

package.json, src/components/variablesComponents/imageVariable/ImageVariable.tsx, src/components/variablesComponents/variablePlaceholder.util.ts, yarn.lock
-   [WRS-2462](https://chilipublishintranet.atlassian.net/browse/WRS-2462)
[WRS-2462]: https://chilipublishintranet.atlassian.net/browse/WRS-2462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix][WRS-2462] Pending state for image picker

documentation/advanced-integration.md
=> [Fix] #309 documentation issues

package.json, yarn.lock
This PR preps for 1.24.0 release
=> [Release] 1.24.0

src/components/variablesComponents/imageVariable/ImageVariable.tsx, src/components/variablesComponents/imageVariable/useUploadAsset.ts, yarn.lock
NOTE: Error handling is not yet implemented
This PR
-   [WRS-2452](https://chilipublishintranet.atlassian.net/browse/WRS-2452)
[WRS-2452]: https://chilipublishintranet.atlassian.net/browse/WRS-2452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Feat][WRS-2452] Use min dimensions config during staging of upload files

package.json, yarn.lock
=> Prep for 1.25 release

.github/workflows/trigger-automated-tests.yml
=> [Fix] Possibility to Skip AQA

src/core/hooks/useVariableTranslations.ts, src/tests/core/hooks/useVariableTranslations.test.ts
This PR
-   [WRS-2519](https://chilipublishintranet.atlassian.net/browse/WRS-2519)
[WRS-2519]: https://chilipublishintranet.atlassian.net/browse/WRS-2519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Feat][WRS-2519] Use variable name as fallback translation key

src/MainContent.tsx, src/components/navbar/Navbar.tsx, src/components/navbar/Navbar.types.ts, src/components/navbar/studioNavbar/StudioNavbar.tsx, src/components/navbar/useDownloadPanel.ts, src/tests/navbar/Navbar.test.tsx, src/tests/navbar/StudioNavbar.test.tsx
This PR
-   [WRS-2421](https://chilipublishintranet.atlassian.net/browse/WRS-2421)
[WRS-2421]: https://chilipublishintranet.atlassian.net/browse/WRS-2421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WRS-2421] Close download modal when selected layout changes

package.json, yarn.lock
=> Prepare 1.26.0 UAT release

__mocks__/mockUserinterface.ts, src/StudioProjectLoader.tsx, src/tests/StudioProjectLoader.test.tsx, src/tests/integration/FormBuilder.test.tsx, src/tests/integration/RequiredVariable.test.tsx, src/tests/utils/formBuilder.test.ts, src/types/types.ts, src/utils/helpers.ts
In addition to defaults, the API interaction was fixed according to the latest version of `formBuilder`property
-   [GRAFX-4850](https://chilipublishintranet.atlassian.net/browse/GRAFX-4850)
[GRAFX-4850]: https://chilipublishintranet.atlassian.net/browse/GRAFX-4850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Feat][GRAFX-4850] Correct default values for formbuilder

.github/workflows/pr-build.yml, jest.config.cjs, sonar-project.properties
As part of this ticket build and test were splitted up onto independent jobs
-   [WRS-1875](https://chilipublishintranet.atlassian.net/browse/WRS-1875)
[WRS-1875]: https://chilipublishintranet.atlassian.net/browse/WRS-1875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Feat][WRS-1875] Setup Sonar Cloud anylize

src/components/navbar/navbarItems/useNavbarMenu.tsx, src/components/navbar/studioNavbar/useStudioNavbar.tsx, src/types/UITranslations.ts
This PR
-   [WRS-2563](https://chilipublishintranet.atlassian.net/browse/WRS-2563)
[WRS-2563]: https://chilipublishintranet.atlassian.net/browse/WRS-2563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Feat][WRS-2563] Add UI translation for hamburger menu items

documentation/advanced-integration.md
=> [Fix] Add missing translations keys

package.json, yarn.lock
=> [Fix] Prepare for 1.28

.github/workflows/production-build.yml, package.json, src/components/variablesComponents/useVariablesComponents.ts, yarn.lock
=> [Hotfix] switch to setImageVariableValueWithContext on SDK patch

package.json, src/MainContent.tsx, src/tests/MainContent.test.tsx, yarn.lock
This PR
-   [WRS-2653](https://chilipublishintranet.atlassian.net/browse/WRS-2653)
[WRS-2653]: https://chilipublishintranet.atlassian.net/browse/WRS-2653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Fix][WRS-2653] Fix zoomtopage on multilayout view

src/_dev-execution/bootstrap.ts
=> chore: restore download btn

src/_dev-execution/bootstrap.ts
=> chore: remove custom implementation of engine initialization

package.json, yarn.lock
=> [Fix] Prepare release 1.30.x
